[project]
name = "scraper_pro"
version = "0.1.0"
description = "一个支持 requests 和 Selenium 的网页采集工具"
authors = [
	{ name = "suifengwudong" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
	"selenium",
	"requests",
	"PyQt5"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
